# Generated by Django 5.2 on 2025-04-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypotlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='honeypotlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='honeypotlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honeypotlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honeypotlog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
