# Generated by Django 5.2 on 2025-04-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_honeypotlog_city_honeypotlog_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypotlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='honeypotlog',
            name='user_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='honeypotlog',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='honeypotlog',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='honeypotlog',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='honeypotlog',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
